name: My First Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Step
        run: echo "Compiling things... Done!"

      - name: Test Step (Check for file)
        run: |
          if [ -f "README.md" ]; then
            echo "Test Passed: README exists!"
          else
            echo "Test Failed: README is missing!"
            exit 1
          fi
