name: Secure Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Step
        run: |
          if [ -f "README.md" ]; then
            echo "Success!"
          else
            exit 1
          fi

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript # You can add python, java, etc.

      - name: Perform Scan
        uses: github/codeql-action/analyze@v3
